In [ ]:
!pip install selenium

In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import datetime
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys


driver=webdriver.Chrome(r"C:\chromedriver.exe")

You have to scrape at least 1500 rows of data. You can scrape more data as well, it’s up to you,
More the data better the model
In this section you have to scrape the data of flights from different websites (yatra.com,
skyscanner.com, official websites of airlines, etc). The number of columns for data doesn’t have
limit, it’s up to you and your creativity. Generally, these columns areairline name, date of journey,
source, destination, route, departure time, arrival time, duration, total stops and the target variable
price. You can make changes to it, you can add or you can remove some columns, it completely
depends on the website from which you are fetching the data

In [2]:
url='https://www.yatra.com/?_ga=2.163528508.1238446844.1635070785-532629679.1635070785'
driver.get(url)

In [3]:
time.sleep(10)
#next button
next_buttons = driver.find_elements_by_xpath('//div[@class="day-li text-center cursor-pointer font-lightgrey"]')      
next_buttons

[]

# finding dates to give as id

In [24]:
#clicking on november
nov=driver.find_element_by_xpath("//p[@class='bold font-lightgrey fs-8 mt-2 text-uppercase']")
nov.click()

#finding elements of each date and storing it which will be accessed later
date=driver.find_elements_by_xpath("//p[@class='date']")
date

[<selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="5399d18a-90ac-40ea-84bf-bafa8398c879")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="36150abb-35bb-4194-b660-b46f3d7b6055")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="11d2f775-f1fa-4c67-a3d4-c7494043ccd2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="8739ed2a-6918-46ee-bc7c-9f146d845b1f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="7aec7f3f-df8a-47f7-bcc7-f86946a8f6bc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="0ae7ba7d-685b-4f8a-a52c-3da164e0842f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="143d76ef-08a1-46f2-90d5-42753af96f31")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="82546eb1-3e95-4ff3-b0e0-3eb398197ca3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="bc5e9fd7-6688-42e6-a0b4-8af4680f2d7c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="3ba7cab4-4604-4876-8919-a67427ccac6e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="1e14050d-cd3c-4264-b705-eaf28ce5777c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="39a0cf57-a2b4-4d9d-8775-31673ac342f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="20d96f4f-261b-4ff7-aa8b-0810eccb5191")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="57fec5af-0401-4288-9262-83e70cda5d82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="7570d411-257b-4df5-9a70-3050f4f73a32")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="5240466f-fa36-49eb-9405-d03c6ee2439b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="66c93d20-ea0f-4235-bebf-3157a29080d8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="fd937d0a-c3d7-4bdd-8c84-e4aaac0418eb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="74530db5-0518-4791-b634-05cad2b88c31")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="5877ee49-06dc-4499-b104-376534d89019")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="6a9dbac8-e256-4e73-b915-5930fcd438ad")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="3017880f-14dd-4e78-b7e6-662b2d2c1fa1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="11eb7bb6-a735-4c7f-a2a4-45d36493ed6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="7dceaec0-deb7-4a89-abe5-de167b995cce")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="3dba5c96-3fa5-41f9-b4b1-9f124bf6b1a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="2fbe8537-54b1-46a6-93ef-760dd15ad2dc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="aea2c6c0-3435-4b8a-b0b0-fe3457c7e466")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="0fbdc441-ed44-46a4-94e0-03ad74084359")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="1669f2f3-c767-4fd8-a052-5333260a2424")>,
 <selenium.webdriver.remote.webelement.WebElement (session="6d47d3a248c099f7dfbb8c0a7f09e890", element="471883b7-421c-4db9-868c-3b7792ccc6d4")>]

In [44]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 1st november")


#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df1=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df1

done for 1st november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"5,953",Air Asia,New Delhi,Mumbai,06:45\n+ 1 day,1 Stop,21:25,1 Nov,Mon
1,"5,953",Air Asia,New Delhi,Mumbai,07:15\n+ 1 day,1 Stop,21:25,1 Nov,Mon
2,"5,953",Air Asia,New Delhi,Mumbai,06:45\n+ 1 day,1 Stop,18:35,1 Nov,Mon
3,"5,953",Air Asia,New Delhi,Mumbai,07:15\n+ 1 day,1 Stop,18:35,1 Nov,Mon
4,"5,953",Air Asia,New Delhi,Mumbai,12:25\n+ 1 day,1 Stop,22:10,1 Nov,Mon
...,...,...,...,...,...,...,...,...,...
155,"12,361",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,1 Nov,Mon
156,"12,413",Vistara,New Delhi,Mumbai,16:55,1 Stop,11:10,1 Nov,Mon
157,"12,659",Go First,New Delhi,Mumbai,18:10,1 Stop,11:50,1 Nov,Mon
158,"13,358",SpiceJet,New Delhi,Mumbai,13:15\n+ 1 day,1 Stop,12:00,1 Nov,Mon
159,"15,931",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,1 Nov,Mon

In [80]:
len(Flightname)

161

In [81]:
len(SourcePlace)

161

In [82]:
len(DestinationPlace)

161

In [83]:
len(ArrivalTime)

161

In [84]:
len(Stop_list)

161

In [85]:
len(Sourcetime)

161

In [46]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 5th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df2=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df2

done for 5th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"5,954",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,5 Nov,Fri
1,"5,954",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,5 Nov,Fri
2,"5,954",Go First,New Delhi,Mumbai,00:40\n+ 1 day,Non Stop,22:30,5 Nov,Fri
3,"5,954",Go First,New Delhi,Mumbai,04:15,Non Stop,02:00,5 Nov,Fri
4,"5,954",Go First,New Delhi,Mumbai,17:15,Non Stop,15:00,5 Nov,Fri
...,...,...,...,...,...,...,...,...,...
157,"17,505",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,5 Nov,Fri
158,"17,558",Vistara,New Delhi,Mumbai,16:55\n+ 1 day,1 Stop,18:40,5 Nov,Fri
159,"18,608",Air India,New Delhi,Mumbai,13:25\n+ 1 day,2 Stop(s),13:15,5 Nov,Fri
160,"19,815",Vistara,New Delhi,Mumbai,16:55,1 Stop,11:10,5 Nov,Fri
161,"19,815",Vistara,New Delhi,Mumbai,23:10,1 Stop,11:10,5 Nov,Fri

In [47]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 10th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df3=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df3

done for 10th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"5,953",Air Asia,New Delhi,Mumbai,02:25\n+ 1 day,1 Stop,20:00,10 Nov,Wed
1,"5,953",Air Asia,New Delhi,Mumbai,06:45\n+ 1 day,1 Stop,21:25,10 Nov,Wed
2,"5,953",Air Asia,New Delhi,Mumbai,07:15\n+ 1 day,1 Stop,21:25,10 Nov,Wed
3,"5,953",Air Asia,New Delhi,Mumbai,06:45\n+ 1 day,1 Stop,20:45,10 Nov,Wed
4,"5,953",Air Asia,New Delhi,Mumbai,07:15\n+ 1 day,1 Stop,20:45,10 Nov,Wed
...,...,...,...,...,...,...,...,...,...
162,"16,928",IndiGo,New Delhi,Mumbai,05:55\n+ 1 day,1 Stop,22:15,10 Nov,Wed
163,"16,928",IndiGo,New Delhi,Mumbai,08:25\n+ 1 day,1 Stop,22:15,10 Nov,Wed
164,"17,295",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,10 Nov,Wed
165,"18,003",Go First,New Delhi,Mumbai,21:25,1 Stop,16:30,10 Nov,Wed
166,"18,003",Go First,New Delhi,Mumbai,02:00\n+ 1 day,1 Stop,20:30,10 Nov,Wed

In [48]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 15th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df4=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df4

done for 15th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"4,931",Air India,New Delhi,Mumbai,09:05,Non Stop,07:00,15 Nov,Mon
1,"4,931",Air India,New Delhi,Mumbai,10:10,Non Stop,08:00,15 Nov,Mon
2,"4,931",Air India,New Delhi,Mumbai,12:50,Non Stop,10:40,15 Nov,Mon
3,"4,931",Air India,New Delhi,Mumbai,20:00,Non Stop,17:50,15 Nov,Mon
4,"4,931",Air India,New Delhi,Mumbai,11:15,Non Stop,09:00,15 Nov,Mon
...,...,...,...,...,...,...,...,...,...
154,"15,459",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,15 Nov,Mon
155,"15,510",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,15 Nov,Mon
156,"15,720",IndiGo,New Delhi,Mumbai,05:55\n+ 1 day,1 Stop,22:15,15 Nov,Mon
157,"15,720",IndiGo,New Delhi,Mumbai,08:25\n+ 1 day,1 Stop,22:15,15 Nov,Mon
158,"20,231",Air India,New Delhi,Mumbai,16:45\n+ 1 day,1 Stop,16:45,15 Nov,Mon

In [49]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 20th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df5=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df5

done for 20th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"4,931",Air India,New Delhi,Mumbai,09:05,Non Stop,07:00,20 Nov,Sat
1,"4,931",Air India,New Delhi,Mumbai,10:10,Non Stop,08:00,20 Nov,Sat
2,"4,931",Air India,New Delhi,Mumbai,12:50,Non Stop,10:40,20 Nov,Sat
3,"4,931",Air India,New Delhi,Mumbai,20:00,Non Stop,17:50,20 Nov,Sat
4,"4,931",Air India,New Delhi,Mumbai,22:10,Non Stop,20:00,20 Nov,Sat
...,...,...,...,...,...,...,...,...,...
163,"13,463",Go First,New Delhi,Mumbai,17:00,1 Stop,09:00,20 Nov,Sat
164,"13,515",Air India,New Delhi,Mumbai,00:10\n+ 2 days,1 Stop,22:00,20 Nov,Sat
165,"15,405",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,20 Nov,Sat
166,"15,405",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,20 Nov,Sat
167,"16,219",SpiceJet,New Delhi,Mumbai,12:35\n+ 1 day,1 Stop,15:00,20 Nov,Sat

In [50]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 25th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df6=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df6

done for 25th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"4,931",Air India,New Delhi,Mumbai,09:05,Non Stop,07:00,25 Nov,Thu
1,"4,931",Air India,New Delhi,Mumbai,10:10,Non Stop,08:00,25 Nov,Thu
2,"4,931",Air India,New Delhi,Mumbai,12:50,Non Stop,10:40,25 Nov,Thu
3,"4,931",Air India,New Delhi,Mumbai,20:00,Non Stop,17:50,25 Nov,Thu
4,"4,931",Air India,New Delhi,Mumbai,22:10,Non Stop,20:00,25 Nov,Thu
...,...,...,...,...,...,...,...,...,...
150,"17,925",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,25 Nov,Thu
151,"17,925",Air India,New Delhi,Mumbai,00:10\n+ 1 day,1 Stop,10:55,25 Nov,Thu
152,"18,083",Vistara,New Delhi,Mumbai,23:10,1 Stop,11:10,25 Nov,Thu
153,"19,081",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,25 Nov,Thu
154,"19,081",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,25 Nov,Thu

In [51]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 30th november")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df7=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df7

done for 30th november

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,30 Nov,Tue
1,"2,456",IndiGo,New Delhi,Mumbai,08:40,Non Stop,06:30,30 Nov,Tue
2,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,30 Nov,Tue
3,"2,456",IndiGo,New Delhi,Mumbai,09:25,Non Stop,07:15,30 Nov,Tue
4,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,30 Nov,Tue
...,...,...,...,...,...,...,...,...,...
142,"10,119",Go First,New Delhi,Mumbai,18:10,1 Stop,12:20,30 Nov,Tue
143,"10,119",Go First,New Delhi,Mumbai,18:10,1 Stop,11:50,30 Nov,Tue
144,"10,119",Go First,New Delhi,Mumbai,18:10,1 Stop,09:15,30 Nov,Tue
145,"10,229",Air India,New Delhi,Mumbai,13:25\n+ 1 day,2 Stop(s),13:15,30 Nov,Tue
146,"16,476",IndiGo,New Delhi,Mumbai,14:50,1 Stop,07:20,30 Nov,Tue

In [53]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 5th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df8=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df8

done for 5th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,5 Dec,Sun
1,"2,456",IndiGo,New Delhi,Mumbai,08:40,Non Stop,06:30,5 Dec,Sun
2,"2,456",IndiGo,New Delhi,Mumbai,09:25,Non Stop,07:15,5 Dec,Sun
3,"2,456",IndiGo,New Delhi,Mumbai,10:20,Non Stop,08:10,5 Dec,Sun
4,"2,456",IndiGo,New Delhi,Mumbai,03:20,Non Stop,01:05,5 Dec,Sun
...,...,...,...,...,...,...,...,...,...
154,"17,589",Go First,New Delhi,Mumbai,14:35,1 Stop,08:40,5 Dec,Sun
155,"17,967",Air India,New Delhi,Mumbai,00:10\n+ 1 day,1 Stop,10:55,5 Dec,Sun
156,"18,514",Go First,New Delhi,Mumbai,17:30,1 Stop,11:50,5 Dec,Sun
157,"19,343",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,5 Dec,Sun
158,"21,600",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,5 Dec,Sun

In [54]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 10th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df9=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df9

done for 10th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,10 Dec,Fri
1,"2,456",IndiGo,New Delhi,Mumbai,08:40,Non Stop,06:30,10 Dec,Fri
2,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,10 Dec,Fri
3,"2,456",IndiGo,New Delhi,Mumbai,09:25,Non Stop,07:15,10 Dec,Fri
4,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,10 Dec,Fri
...,...,...,...,...,...,...,...,...,...
148,"14,375",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,10 Dec,Fri
149,"14,375",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,10 Dec,Fri
150,"16,392",Air India,New Delhi,Mumbai,00:10\n+ 1 day,1 Stop,10:55,10 Dec,Fri
151,"16,613",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,10 Dec,Fri
152,"17,967",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,10 Dec,Fri

In [55]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 15th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df10=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df10

done for 15th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,15 Dec,Wed
1,"2,456",IndiGo,New Delhi,Mumbai,08:40,Non Stop,06:30,15 Dec,Wed
2,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,15 Dec,Wed
3,"2,456",IndiGo,New Delhi,Mumbai,09:25,Non Stop,07:15,15 Dec,Wed
4,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,15 Dec,Wed
...,...,...,...,...,...,...,...,...,...
154,"11,652",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,15 Dec,Wed
155,"12,252",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,15 Dec,Wed
156,"18,188",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,15 Dec,Wed
157,"18,702",Air India,New Delhi,Mumbai,00:10\n+ 1 day,1 Stop,10:55,15 Dec,Wed
158,"19,227",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,15 Dec,Wed

In [56]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 20th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df11=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df11

done for 20th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,20 Dec,Mon
1,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,20 Dec,Mon
2,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,20 Dec,Mon
3,"2,456",IndiGo,New Delhi,Mumbai,10:20,Non Stop,08:10,20 Dec,Mon
4,"2,456",IndiGo,New Delhi,Mumbai,19:25,Non Stop,17:15,20 Dec,Mon
...,...,...,...,...,...,...,...,...,...
147,"10,443",Air India,New Delhi,Mumbai,08:45\n+ 1 day,1 Stop,10:55,20 Dec,Mon
148,"10,754",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,20 Dec,Mon
149,"11,068",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,20 Dec,Mon
150,"11,283",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,20 Dec,Mon
151,"12,658",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,20 Dec,Mon

In [57]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 25th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df12=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df12

done for 25th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",IndiGo,New Delhi,Mumbai,10:20,Non Stop,08:10,25 Dec,Sat
1,"2,456",IndiGo,New Delhi,Mumbai,19:25,Non Stop,17:15,25 Dec,Sat
2,"2,456",Go First,New Delhi,Mumbai,00:40\n+ 1 day,Non Stop,22:30,25 Dec,Sat
3,"2,456",IndiGo,New Delhi,Mumbai,03:20,Non Stop,01:05,25 Dec,Sat
4,"2,456",Go First,New Delhi,Mumbai,04:15,Non Stop,02:00,25 Dec,Sat
...,...,...,...,...,...,...,...,...,...
162,"10,353",Go First,New Delhi,Mumbai,18:10,1 Stop,12:20,25 Dec,Sat
163,"10,833",Go First,New Delhi,Mumbai,18:10,1 Stop,11:50,25 Dec,Sat
164,"11,177",Go First,New Delhi,Mumbai,18:10,1 Stop,09:15,25 Dec,Sat
165,"13,954",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,25 Dec,Sat
166,"14,268",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,25 Dec,Sat

In [58]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 30th december")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df13=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df13

done for 30th december

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,30 Dec,Thu
1,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,30 Dec,Thu
2,"2,456",Go First,New Delhi,Mumbai,04:15,Non Stop,02:00,30 Dec,Thu
3,"2,456",SpiceJet,New Delhi,Mumbai,09:35,Non Stop,07:20,30 Dec,Thu
4,"2,456",Go First,New Delhi,Mumbai,17:15,Non Stop,15:00,30 Dec,Thu
...,...,...,...,...,...,...,...,...,...
144,"13,389",IndiGo,New Delhi,Mumbai,14:50,1 Stop,07:20,30 Dec,Thu
145,"13,425",Go First,New Delhi,Mumbai,19:40,1 Stop,10:45,30 Dec,Thu
146,"14,268",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,30 Dec,Thu
147,"14,660",Vistara,New Delhi,Mumbai,14:45\n+ 1 day,1 Stop,18:40,30 Dec,Thu
148,"15,416",Vistara,New Delhi,Mumbai,23:10,1 Stop,11:10,30 Dec,Thu

In [59]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 5th January")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df14=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df14

done for 5th January

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,5 Jan,Wed
1,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,5 Jan,Wed
2,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,5 Jan,Wed
3,"2,456",SpiceJet,New Delhi,Mumbai,21:05,Non Stop,18:55,5 Jan,Wed
4,"2,456",Go First,New Delhi,Mumbai,04:15,Non Stop,02:00,5 Jan,Wed
...,...,...,...,...,...,...,...,...,...
155,"8,790",Vistara,New Delhi,Mumbai,16:00,1 Stop,10:55,5 Jan,Wed
156,"9,544",Go First,New Delhi,Mumbai,18:20,1 Stop,10:45,5 Jan,Wed
157,"9,918",Air India,New Delhi,Mumbai,16:35,1 Stop,10:55,5 Jan,Wed
158,"12,553",Air India,New Delhi,Mumbai,22:25,1 Stop,10:55,5 Jan,Wed
159,"13,389",IndiGo,New Delhi,Mumbai,14:50,1 Stop,07:20,5 Jan,Wed

In [60]:
Price=[]
Dateday=[]
Flightname=[]   
Sourceplace=[]
SourcePlace=[]
Arrivaltimedestination=[]
DestinationPlace=[]
ArrivalTime=[]
Timetaken=[]
Stops=[]
Stop_list=[]
Sourcetime=[]



price=driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append("--")


dateday=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in dateday:
    try:
        Dateday.append(i.text)
    except NoSuchElementException:
        Dateday.append("--")       


flightname=driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")
for i in flightname:
    try:
        Flightname.append(i.text)
    except NoSuchElementException:
        Flightname.append("--")

#sourceplace
sourceplace=driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']//p")
for i in sourceplace:
    try:
        Sourceplace.append(i.text)
    except NoSuchElementException:
        Sourceplace.append("--")

#finding second elements
for i in range(1,len(Sourceplace),2):
    SourcePlace.append(Sourceplace[i])


arrivaltimedestination=driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']//p")
for i in arrivaltimedestination:
    try:
        Arrivaltimedestination.append(i.text)
    except NoSuchElementException:
        Arrivaltimedestination.append("--")

#finding second elements 
for i in range(1,len(Arrivaltimedestination),2):
    DestinationPlace.append(Arrivaltimedestination[i])

for i in range(0,len(Arrivaltimedestination),2):
    ArrivalTime.append(Arrivaltimedestination[i])

#timetaken
timetaken=driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")
for i in timetaken:
    try:
        Timetaken.append(i.text)
    except NoSuchElementException:
        Timetaken.append("--")
#stops
stops=driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']")
for i in stops:
    try:
        Stops.append(i.text)
    except NoSuchElementException:
        Stops.append("--")

#finding number of stops
for i in range(len(Stops)):
           a,b = Stops[i].split("\n")
           Stop_list.append(b)

#source time
sourcetime=driver.find_elements_by_xpath("//div[@class='i-b pr']")
for i in sourcetime:
    try:
        Sourcetime.append(i.text)
    except NoSuchElementException:
        Sourcetime.append("--")           
print("done for 10th January")

#finding date and day
Dateday=[]
Datedayprice=[]
Date=[]
day=[]

datedayprice=driver.find_elements_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']//p")
for i in datedayprice:
    try:
        Datedayprice.append(i.text)
    except NoSuchElementException:
        Datedayprice.append("--")
        
#finding second elements
for i in range(0,len(Datedayprice),2):
    Dateday.append(Datedayprice[i])
    

#split Dateday into date and day
datedaylist=Dateday[0].split(',')
day=datedaylist[0]
date=datedaylist[1]

Date1=[]
day1=[]

a=len(Price)
for k in range(a):
    Date1.append(date)
    day1.append(day)


df15=pd.DataFrame({'Price':Price,
                'Flightname':Flightname,
                 'Sourceplace':SourcePlace,
                'DestinationPlace':DestinationPlace,
                 'ArrivalTime':ArrivalTime,
                'Stops':Stop_list,
                'Sourcetime':Sourcetime,
                  'Date':Date1,
                   'day':day1
                })
df15

done for 10th January

,Price,Flightname,Sourceplace,DestinationPlace,ArrivalTime,Stops,Sourcetime,Date,day
0,"2,456",Air Asia,New Delhi,Mumbai,06:35,Non Stop,04:25,10 Jan,Mon
1,"2,456",Go First,New Delhi,Mumbai,09:10,Non Stop,07:00,10 Jan,Mon
2,"2,456",Go First,New Delhi,Mumbai,10:10,Non Stop,08:00,10 Jan,Mon
3,"2,456",Go First,New Delhi,Mumbai,00:40\n+ 1 day,Non Stop,22:30,10 Jan,Mon
4,"2,456",Go First,New Delhi,Mumbai,04:15,Non Stop,02:00,10 Jan,Mon
...,...,...,...,...,...,...,...,...,...
163,"8,921",Go First,New Delhi,Mumbai,18:10,1 Stop,12:20,10 Jan,Mon
164,"8,921",Go First,New Delhi,Mumbai,18:10,1 Stop,09:15,10 Jan,Mon
165,"9,399",Go First,New Delhi,Mumbai,18:10,1 Stop,11:50,10 Jan,Mon
166,"11,661",Air India,New Delhi,Mumbai,00:10\n+ 1 day,1 Stop,10:55,10 Jan,Mon
167,"13,389",IndiGo,New Delhi,Mumbai,14:50,1 Stop,07:20,10 Jan,Mon

In [61]:
#appending all the dataframes together and storing in df dataframe
df1append=df1.append(df2)
df2append=df1append.append(df3)
df3append=df2append.append(df4)
df4append=df3append.append(df5)
df5append=df4append.append(df6)
df6append=df5append.append(df7)
df7append=df6append.append(df8)
df8append=df7append.append(df9)
df9append=df8append.append(df10)
df10append=df9append.append(df11)
df11append=df10append.append(df12)
df12append=df11append.append(df13)
df13append=df12append.append(df14)
df14append=df13append.append(df15)
len(df14append)

2385

In [62]:
df_final=df14append

In [63]:
df_final.to_excel("flight.xlsx", index = False)

2071 data is mined from yatra and stored in excel sheet named flight